name: Commit Message Check

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Squash Commit Message (PR Title)
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          if ! [[ "$pr_title" =~ ^[^\n]{1,50}$ && "$pr_title" =~ SCRUM[0-9]+ ]]; then
            echo "Invalid PR title for squash commit: $pr_title"
            exit 1
          fi
